use std::path::Path;

use serde_json::{json, Value as JsonValue};
use tracing::{info, warn};

/// Generate default ACL configuration from annotated bindings.
///
/// Categorizes bindings into readonly, destructive, and write groups,
/// producing rules for each non-empty group.
pub fn generate_acl(
    bindings: &[serde_json::Map<String, JsonValue>],
    default_effect: &str,
) -> serde_json::Map<String, JsonValue> {
    let mut rules: Vec<JsonValue> = Vec::new();

    let readonly_ids: Vec<&str> = bindings
        .iter()
        .filter(|b| {
            b.get("annotations")
                .and_then(|a| a.get("readonly"))
                .and_then(|v| v.as_bool())
                .unwrap_or(false)
        })
        .filter_map(|b| b.get("module_id")?.as_str())
        .collect();

    if !readonly_ids.is_empty() {
        rules.push(json!({
            "callers": ["@external", "*"],
            "targets": readonly_ids,
            "effect": "allow",
            "description": "Auto-allow readonly CLI commands",
        }));
    }

    let destructive_ids: Vec<&str> = bindings
        .iter()
        .filter(|b| {
            b.get("annotations")
                .and_then(|a| a.get("destructive"))
                .and_then(|v| v.as_bool())
                .unwrap_or(false)
        })
        .filter_map(|b| b.get("module_id")?.as_str())
        .collect();

    if !destructive_ids.is_empty() {
        rules.push(json!({
            "callers": ["@external", "*"],
            "targets": destructive_ids,
            "effect": "allow",
            "description": "Destructive CLI commands (requires_approval enforced at module level)",
        }));
    }

    let write_ids: Vec<&str> = bindings
        .iter()
        .filter(|b| {
            let annotations = b.get("annotations");
            let is_readonly = annotations
                .and_then(|a| a.get("readonly"))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let is_destructive = annotations
                .and_then(|a| a.get("destructive"))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            !is_readonly && !is_destructive
        })
        .filter_map(|b| b.get("module_id")?.as_str())
        .collect();

    if !write_ids.is_empty() {
        rules.push(json!({
            "callers": ["@external", "*"],
            "targets": write_ids,
            "effect": "allow",
            "description": "Non-destructive write CLI commands",
        }));
    }

    let mut acl = serde_json::Map::new();
    acl.insert("$schema".to_string(), json!("https://apcore.dev/acl/v1"));
    acl.insert("version".to_string(), json!("1.0.0"));
    acl.insert("rules".to_string(), JsonValue::Array(rules));
    acl.insert("default_effect".to_string(), json!(default_effect));
    acl.insert(
        "audit".to_string(),
        json!({
            "enabled": true,
            "log_level": "info",
            "include_denied": true,
        }),
    );
    acl
}

/// Write ACL configuration to a YAML file.
///
/// Non-fatal: logs warnings on failure but does not return errors.
pub fn write_acl(acl_config: &serde_json::Map<String, JsonValue>, output_path: &Path) {
    if let Some(parent) = output_path.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            warn!(path = %output_path.display(), "Failed to create ACL directory: {e}");
            return;
        }
    }

    let yaml_value = JsonValue::Object(acl_config.clone());
    let yaml_str = match serde_yaml::to_string(&yaml_value) {
        Ok(s) => s,
        Err(e) => {
            warn!("Failed to serialize ACL to YAML: {e}");
            return;
        }
    };

    let content = format!("# Auto-generated by apexe. Edit to customize.\n{yaml_str}");
    match std::fs::write(output_path, content) {
        Ok(()) => info!(path = %output_path.display(), "ACL written"),
        Err(e) => warn!(path = %output_path.display(), "Failed to write ACL: {e}"),
    }
}

/// Load ACL configuration from a YAML file.
///
/// Returns None if the file does not exist.
pub fn load_acl(path: &Path) -> Option<serde_json::Map<String, JsonValue>> {
    if !path.exists() {
        return None;
    }

    let contents = match std::fs::read_to_string(path) {
        Ok(c) => c,
        Err(e) => {
            warn!(path = %path.display(), "Failed to read ACL file: {e}");
            return None;
        }
    };

    match serde_yaml::from_str::<JsonValue>(&contents) {
        Ok(JsonValue::Object(map)) => Some(map),
        Ok(_) => {
            warn!(path = %path.display(), "ACL file is not a YAML mapping");
            None
        }
        Err(e) => {
            warn!(path = %path.display(), "Failed to parse ACL YAML: {e}");
            None
        }
    }
}

/// Check whether a caller has access to a target module based on ACL rules.
///
/// Supports wildcard patterns: `*` matches everything, `cli.*` matches prefix.
pub fn check_access(acl: &serde_json::Map<String, JsonValue>, caller: &str, target: &str) -> bool {
    let default_effect = acl
        .get("default_effect")
        .and_then(|v| v.as_str())
        .unwrap_or("deny");

    let rules = match acl.get("rules").and_then(|v| v.as_array()) {
        Some(r) => r,
        None => return default_effect == "allow",
    };

    for rule in rules {
        let effect = rule
            .get("effect")
            .and_then(|v| v.as_str())
            .unwrap_or("deny");

        let callers_match = rule
            .get("callers")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter().any(|c| {
                    let pattern = c.as_str().unwrap_or("");
                    pattern_matches(pattern, caller)
                })
            })
            .unwrap_or(false);

        let targets_match = rule
            .get("targets")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter().any(|t| {
                    let pattern = t.as_str().unwrap_or("");
                    pattern_matches(pattern, target)
                })
            })
            .unwrap_or(false);

        if callers_match && targets_match {
            return effect == "allow";
        }
    }

    default_effect == "allow"
}

/// Match a pattern against a value with wildcard support.
///
/// - `*` matches everything
/// - `cli.*` matches any string starting with `cli.`
/// - Exact match otherwise
fn pattern_matches(pattern: &str, value: &str) -> bool {
    if pattern == "*" {
        return true;
    }
    if let Some(prefix) = pattern.strip_suffix('*') {
        return value.starts_with(prefix);
    }
    pattern == value
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn make_binding_map(
        module_id: &str,
        readonly: bool,
        destructive: bool,
    ) -> serde_json::Map<String, JsonValue> {
        let mut m = serde_json::Map::new();
        m.insert("module_id".to_string(), json!(module_id));
        m.insert(
            "annotations".to_string(),
            json!({
                "readonly": readonly,
                "destructive": destructive,
            }),
        );
        m
    }

    // T6: ACL generation
    #[test]
    fn test_generate_acl_mixed_bindings() {
        let bindings = vec![
            make_binding_map("cli.git.status", true, false),
            make_binding_map("cli.git.log", true, false),
            make_binding_map("cli.git.clean", false, true),
            make_binding_map("cli.git.commit", false, false),
            make_binding_map("cli.git.push", false, false),
        ];

        let acl = generate_acl(&bindings, "deny");

        let rules = acl["rules"].as_array().unwrap();
        assert_eq!(rules.len(), 3);
        assert_eq!(acl["default_effect"], "deny");
        assert_eq!(acl["$schema"], "https://apcore.dev/acl/v1");
        assert_eq!(acl["version"], "1.0.0");
    }

    #[test]
    fn test_generate_acl_empty_bindings() {
        let acl = generate_acl(&[], "deny");
        let rules = acl["rules"].as_array().unwrap();
        assert!(rules.is_empty());
    }

    #[test]
    fn test_generate_acl_only_readonly() {
        let bindings = vec![
            make_binding_map("cli.git.status", true, false),
            make_binding_map("cli.git.log", true, false),
        ];

        let acl = generate_acl(&bindings, "deny");
        let rules = acl["rules"].as_array().unwrap();
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0]["description"], "Auto-allow readonly CLI commands");
    }

    #[test]
    fn test_generate_acl_default_effect_allow() {
        let acl = generate_acl(&[], "allow");
        assert_eq!(acl["default_effect"], "allow");
    }

    #[test]
    fn test_generate_acl_audit_block() {
        let acl = generate_acl(&[], "deny");
        assert!(acl["audit"]["enabled"].as_bool().unwrap());
    }

    // T7: ACL YAML writer
    #[test]
    fn test_write_acl_creates_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("acl.yaml");
        let acl = generate_acl(&[], "deny");

        write_acl(&acl, &path);

        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("# Auto-generated by apexe"));
    }

    #[test]
    fn test_write_acl_creates_parent_dirs() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("subdir").join("acl.yaml");
        let acl = generate_acl(&[], "deny");

        write_acl(&acl, &path);

        assert!(path.exists());
    }

    #[test]
    fn test_write_acl_roundtrip() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("acl.yaml");

        let bindings = vec![
            make_binding_map("cli.git.status", true, false),
            make_binding_map("cli.git.clean", false, true),
        ];
        let acl = generate_acl(&bindings, "deny");

        write_acl(&acl, &path);

        let content = std::fs::read_to_string(&path).unwrap();
        let parsed: JsonValue = serde_yaml::from_str(&content).unwrap();
        let rules = parsed["rules"].as_array().unwrap();
        assert_eq!(rules.len(), 2);
    }

    // T8: ACL loader and check_access
    #[test]
    fn test_load_acl_existing_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("acl.yaml");

        let acl = generate_acl(&[], "deny");
        write_acl(&acl, &path);

        let loaded = load_acl(&path);
        assert!(loaded.is_some());
    }

    #[test]
    fn test_load_acl_missing_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("nonexistent.yaml");
        assert!(load_acl(&path).is_none());
    }

    #[test]
    fn test_check_access_wildcard_caller() {
        let bindings = vec![make_binding_map("cli.git.status", true, false)];
        let acl = generate_acl(&bindings, "deny");

        assert!(check_access(&acl, "@external", "cli.git.status"));
    }

    #[test]
    fn test_check_access_default_deny() {
        let acl = generate_acl(&[], "deny");
        assert!(!check_access(&acl, "@external", "cli.git.status"));
    }

    #[test]
    fn test_check_access_default_allow() {
        let acl = generate_acl(&[], "allow");
        assert!(check_access(&acl, "@external", "cli.git.status"));
    }

    #[test]
    fn test_pattern_matches_exact() {
        assert!(pattern_matches("cli.git.status", "cli.git.status"));
        assert!(!pattern_matches("cli.git.status", "cli.git.log"));
    }

    #[test]
    fn test_pattern_matches_star() {
        assert!(pattern_matches("*", "anything"));
    }

    #[test]
    fn test_pattern_matches_prefix_wildcard() {
        assert!(pattern_matches("cli.*", "cli.git.status"));
        assert!(pattern_matches("cli.git.*", "cli.git.status"));
        assert!(!pattern_matches("cli.docker.*", "cli.git.status"));
    }
}
