use std::path::{Path, PathBuf};

use tracing::info;

use super::binding_gen::GeneratedBindingFile;
use crate::errors::ApexeError;

/// Serializes GeneratedBindingFile to YAML files.
pub struct BindingYAMLWriter;

impl BindingYAMLWriter {
    /// Write binding file to disk.
    ///
    /// Returns the path to the written file.
    pub fn write(
        &self,
        binding_file: &GeneratedBindingFile,
        output_dir: &Path,
    ) -> Result<PathBuf, ApexeError> {
        std::fs::create_dir_all(output_dir)?;

        let yaml_data = serde_json::json!({
            "bindings": binding_file.bindings,
        });
        let yaml_str = serde_yaml::to_string(&yaml_data)?;
        let content = format!("# Auto-generated by apexe. Edit to customize.\n{yaml_str}");

        let file_path = output_dir.join(&binding_file.file_name);
        std::fs::write(&file_path, content)?;

        info!(path = %file_path.display(), count = binding_file.bindings.len(), "Wrote binding file");

        Ok(file_path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::binding::binding_gen::{GeneratedBinding, GeneratedBindingFile};
    use serde_json::json;
    use std::collections::HashMap;

    fn make_binding_file() -> GeneratedBindingFile {
        GeneratedBindingFile {
            tool_name: "git".to_string(),
            file_name: "git.binding.yaml".to_string(),
            bindings: vec![
                GeneratedBinding {
                    module_id: "cli.git.status".to_string(),
                    description: "Show working tree status".to_string(),
                    target: "apexe::executor::execute_cli".to_string(),
                    input_schema: json!({
                        "type": "object",
                        "properties": {
                            "short": {"type": "boolean", "default": false}
                        },
                        "additionalProperties": false,
                    }),
                    output_schema: json!({
                        "type": "object",
                        "properties": {
                            "stdout": {"type": "string"},
                            "stderr": {"type": "string"},
                            "exit_code": {"type": "integer"},
                        },
                        "required": ["stdout", "stderr", "exit_code"],
                    }),
                    tags: vec!["cli".to_string(), "git".to_string()],
                    version: "1.0.0".to_string(),
                    annotations: HashMap::new(),
                    metadata: {
                        let mut m = HashMap::new();
                        m.insert("apexe_binary".to_string(), json!("git"));
                        m.insert("apexe_command".to_string(), json!(["git", "status"]));
                        m.insert("apexe_timeout".to_string(), json!(30));
                        m
                    },
                },
                GeneratedBinding {
                    module_id: "cli.git.commit".to_string(),
                    description: "Record changes".to_string(),
                    target: "apexe::executor::execute_cli".to_string(),
                    input_schema: json!({"type": "object", "properties": {}}),
                    output_schema: json!({"type": "object"}),
                    tags: vec!["cli".to_string(), "git".to_string()],
                    version: "1.0.0".to_string(),
                    annotations: HashMap::new(),
                    metadata: HashMap::new(),
                },
            ],
        }
    }

    #[test]
    fn test_write_creates_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let binding_file = make_binding_file();
        let writer = BindingYAMLWriter;

        let path = writer.write(&binding_file, tmp.path()).unwrap();

        assert!(path.exists());
        assert_eq!(path.file_name().unwrap(), "git.binding.yaml");
    }

    #[test]
    fn test_write_starts_with_header() {
        let tmp = tempfile::TempDir::new().unwrap();
        let binding_file = make_binding_file();
        let writer = BindingYAMLWriter;

        let path = writer.write(&binding_file, tmp.path()).unwrap();
        let content = std::fs::read_to_string(path).unwrap();

        assert!(content.starts_with("# Auto-generated by apexe"));
    }

    #[test]
    fn test_write_valid_yaml() {
        let tmp = tempfile::TempDir::new().unwrap();
        let binding_file = make_binding_file();
        let writer = BindingYAMLWriter;

        let path = writer.write(&binding_file, tmp.path()).unwrap();
        let content = std::fs::read_to_string(path).unwrap();

        // Strip the comment line for parsing
        let yaml_content: String = content
            .lines()
            .filter(|line| !line.starts_with('#'))
            .collect::<Vec<&str>>()
            .join("\n");
        let parsed: serde_yaml::Value = serde_yaml::from_str(&yaml_content).unwrap();

        let bindings = parsed["bindings"].as_sequence().unwrap();
        assert_eq!(bindings.len(), 2);
    }

    #[test]
    fn test_write_round_trip() {
        let tmp = tempfile::TempDir::new().unwrap();
        let binding_file = make_binding_file();
        let writer = BindingYAMLWriter;

        let path = writer.write(&binding_file, tmp.path()).unwrap();
        let content = std::fs::read_to_string(path).unwrap();

        // Strip comment for parsing
        let yaml_content: String = content
            .lines()
            .filter(|line| !line.starts_with('#'))
            .collect::<Vec<&str>>()
            .join("\n");

        #[derive(serde::Deserialize)]
        struct BindingDoc {
            bindings: Vec<GeneratedBinding>,
        }

        let doc: BindingDoc = serde_yaml::from_str(&yaml_content).unwrap();
        assert_eq!(doc.bindings.len(), 2);
        assert_eq!(doc.bindings[0].module_id, "cli.git.status");
        assert_eq!(doc.bindings[1].module_id, "cli.git.commit");
    }

    #[test]
    fn test_write_creates_directories() {
        let tmp = tempfile::TempDir::new().unwrap();
        let nested = tmp.path().join("a").join("b").join("c");
        let binding_file = make_binding_file();
        let writer = BindingYAMLWriter;

        let path = writer.write(&binding_file, &nested).unwrap();
        assert!(path.exists());
    }
}
