use std::collections::HashMap;

use serde_json::json;

use apexe::binding::binding_gen::GeneratedBinding;
use apexe::governance::acl::{generate_acl, write_acl};
use apexe::governance::annotations::annotate_bindings;
use apexe::governance::audit::{AuditEntry, AuditLogger};

fn make_test_binding(module_id: &str, description: &str) -> GeneratedBinding {
    GeneratedBinding {
        module_id: module_id.to_string(),
        description: description.to_string(),
        target: "apexe::executor::execute_cli".to_string(),
        input_schema: json!({}),
        output_schema: json!({}),
        tags: vec!["cli".to_string()],
        version: "1.0.0".to_string(),
        annotations: HashMap::new(),
        metadata: HashMap::new(),
    }
}

/// T14: End-to-end integration test for the governance pipeline.
#[test]
fn test_full_governance_pipeline() {
    // Step 1: Create mock bindings for a git-like tool
    let mut bindings = vec![
        make_test_binding("cli.git.status", "Show the working tree status"),
        make_test_binding("cli.git.commit", "Record changes to the repository"),
        make_test_binding("cli.git.rm", "Remove files from the working tree"),
    ];

    // Step 2: Run annotation inference
    annotate_bindings(&mut bindings);

    // Verify: status = readonly
    assert_eq!(bindings[0].annotations["readonly"], json!(true));
    assert_eq!(bindings[0].annotations["destructive"], json!(false));

    // Verify: commit = not readonly, not destructive (write)
    assert_eq!(bindings[1].annotations["readonly"], json!(false));
    assert_eq!(bindings[1].annotations["destructive"], json!(false));

    // Verify: rm = destructive + requires_approval
    assert_eq!(bindings[2].annotations["destructive"], json!(true));
    assert_eq!(bindings[2].annotations["requires_approval"], json!(true));

    // Verify all bindings have confidence metadata
    for binding in &bindings {
        assert!(binding.metadata.contains_key("apexe_annotation_confidence"));
        assert!(binding.metadata.contains_key("apexe_annotation_reasoning"));
    }

    // Step 3: Convert to ACL input format and generate ACL
    let acl_bindings: Vec<serde_json::Map<String, serde_json::Value>> = bindings
        .iter()
        .map(|b| {
            let mut m = serde_json::Map::new();
            m.insert(
                "module_id".to_string(),
                serde_json::Value::String(b.module_id.clone()),
            );
            m.insert("annotations".to_string(), json!(b.annotations));
            m
        })
        .collect();

    let acl = generate_acl(&acl_bindings, "deny");

    // Verify: 3 rule groups (readonly, destructive, write)
    let rules = acl["rules"].as_array().unwrap();
    assert_eq!(rules.len(), 3);
    assert_eq!(acl["default_effect"], "deny");

    // Step 4: Write ACL to disk
    let tmp = tempfile::TempDir::new().unwrap();
    let acl_path = tmp.path().join("acl.yaml");
    write_acl(&acl, &acl_path);

    // Verify YAML file exists and is valid
    assert!(acl_path.exists());
    let yaml_content = std::fs::read_to_string(&acl_path).unwrap();
    assert!(yaml_content.starts_with("# Auto-generated by apexe"));
    let parsed: serde_json::Value = serde_yaml::from_str(&yaml_content).unwrap();
    assert!(parsed["rules"].is_array());

    // Step 5: Create AuditLogger and log entries
    let audit_path = tmp.path().join("audit.jsonl");
    let logger = AuditLogger::new(audit_path.clone());

    for binding in &bindings {
        let entry = AuditEntry {
            module_id: binding.module_id.clone(),
            caller_id: "@external".to_string(),
            inputs_hash: AuditLogger::hash_inputs(&serde_json::Map::new()),
            ..Default::default()
        };
        logger.log(&entry);
    }

    // Step 6: Verify audit log
    let audit_content = std::fs::read_to_string(&audit_path).unwrap();
    let lines: Vec<&str> = audit_content.lines().collect();
    assert_eq!(lines.len(), 3);

    // Verify each line has correct module_id and non-empty hash
    let expected_ids = ["cli.git.status", "cli.git.commit", "cli.git.rm"];
    for (i, line) in lines.iter().enumerate() {
        let parsed: AuditEntry = serde_json::from_str(line).unwrap();
        assert_eq!(parsed.module_id, expected_ids[i]);
        assert!(!parsed.inputs_hash.is_empty());
        assert!(!parsed.trace_id.is_empty());
        assert!(!parsed.timestamp.is_empty());
    }
}
